# this file is autogenerated by .github/workflows/update.yml
{
  url = "https://github.com/Xenonus/nix-index-database/releases/download/2026-09-27-083550/index-";
  hashes = {
    x86_64-linux = "sha256-6xo6GeMhWlZPrXtZ3h873IJAX7qiZ6FZu1gJW4Jlq1Q=";
    x86_64-linux-small = "sha256-M58rEBU/y0YpOOvWJddkn50PPxyJF/Wkm4WW5mkQ6R0=";
  };
}
