# this file is autogenerated by .github/workflows/update.yml
{
  url = "https://github.com/Xenonus/nix-index-database/releases/download/2026-08-30-085208/index-";
  hashes = {
    x86_64-linux = "sha256-kAXPU8d8mdfBQYfek3yNgcEwh6GGE2lNOBYL0x9+rjE=";
    x86_64-linux-small = "sha256-V8ki4Xg9bRfqQTg9iyb4K0f25Hlen6v2H3F+52ef/2g=";
  };
}
