# this file is autogenerated by .github/workflows/update.yml
{
  url = "https://github.com/Xenonus/nix-index-database/releases/download/2026-08-23-033830/index-";
  hashes = {
    x86_64-linux = "sha256-2tRpalvKEDyDcqXZx9YhCIazU/m6Q8BRZhOdG16gNuc=";
    x86_64-linux-small = "sha256-IkubjsU8gJWZyD4TzIzrUnQL/JK8dVhc7ENiiUUqikY=";
  };
}
